# ============================================================
# LOCAL DEVELOPER PROFILE  —  DO NOT USE IN PRODUCTION
# Run with:  mvn spring-boot:run "-Dspring-boot.run.profiles=local"
# ============================================================

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: patient-service
          uri: http://localhost:7081
          predicates:
            - Path=/api/v1/patients/**, /api/v1/organizations/**, /api/v1/practitioners/**

        - id: clinical-service
          uri: http://localhost:7082
          predicates:
            - Path=/api/v1/encounters/**, /api/v1/observations/**, /api/v1/conditions/**, /api/v1/medications/**

        - id: billing-service
          uri: http://localhost:7083
          predicates:
            - Path=/api/v1/coverage/**, /api/v1/payers/**

        - id: portal-service
          uri: http://localhost:7084
          predicates:
            - Path=/api/v1/appointments/**, /api/v1/messages/**, /api/v1/consents/**

        - id: audit-service
          uri: http://localhost:7085
          predicates:
            - Path=/api/v1/audit/**

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.resource.reactive.ReactiveOAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.healthcare.gateway: DEBUG
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
